In [2]:
import numpy as np

docs = ['python is great',
        'machine learning rules',
        'clean code always',
        'debug till it works',
        'git commit and push',
        'stack overflow saves lives',
        'artificial intelligence future',
        'keep it simple stupid',
        'syntax error found',
        'hello world program']

In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token = 'nothing')

In [4]:
tokenizer.fit_on_texts(docs)

In [5]:
tokenizer.word_index

{'nothing': 1,
 'it': 2,
 'python': 3,
 'is': 4,
 'great': 5,
 'machine': 6,
 'learning': 7,
 'rules': 8,
 'clean': 9,
 'code': 10,
 'always': 11,
 'debug': 12,
 'till': 13,
 'works': 14,
 'git': 15,
 'commit': 16,
 'and': 17,
 'push': 18,
 'stack': 19,
 'overflow': 20,
 'saves': 21,
 'lives': 22,
 'artificial': 23,
 'intelligence': 24,
 'future': 25,
 'keep': 26,
 'simple': 27,
 'stupid': 28,
 'syntax': 29,
 'error': 30,
 'found': 31,
 'hello': 32,
 'world': 33,
 'program': 34}

In [6]:
tokenizer.word_counts

OrderedDict([('python', 1),
             ('is', 1),
             ('great', 1),
             ('machine', 1),
             ('learning', 1),
             ('rules', 1),
             ('clean', 1),
             ('code', 1),
             ('always', 1),
             ('debug', 1),
             ('till', 1),
             ('it', 2),
             ('works', 1),
             ('git', 1),
             ('commit', 1),
             ('and', 1),
             ('push', 1),
             ('stack', 1),
             ('overflow', 1),
             ('saves', 1),
             ('lives', 1),
             ('artificial', 1),
             ('intelligence', 1),
             ('future', 1),
             ('keep', 1),
             ('simple', 1),
             ('stupid', 1),
             ('syntax', 1),
             ('error', 1),
             ('found', 1),
             ('hello', 1),
             ('world', 1),
             ('program', 1)])

In [7]:
tokenizer.document_count

10

In [8]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[3, 4, 5],
 [6, 7, 8],
 [9, 10, 11],
 [12, 13, 2, 14],
 [15, 16, 17, 18],
 [19, 20, 21, 22],
 [23, 24, 25],
 [26, 2, 27, 28],
 [29, 30, 31],
 [32, 33, 34]]

In [9]:
from keras.utils import pad_sequences

In [10]:
sequences = pad_sequences(sequences,padding = 'post')

In [11]:
sequences

array([[ 3,  4,  5,  0],
       [ 6,  7,  8,  0],
       [ 9, 10, 11,  0],
       [12, 13,  2, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25,  0],
       [26,  2, 27, 28],
       [29, 30, 31,  0],
       [32, 33, 34,  0]], dtype=int32)

In [8]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [13]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [14]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [15]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [16]:
X_train = pad_sequences(X_train, padding='post', maxlen=50)
X_test = pad_sequences(X_test, padding='post', maxlen=50)

In [17]:
X_train.shape

(25000, 50)

In [18]:
model = Sequential()

model.add(SimpleRNN(32,input_shape = (50,1),return_sequences = False))
model.add(Dense(1,activation = 'sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [19]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding

# Define the vocabulary size (num_words used in imdb.load_data) and maxlen
vocab_size = 10000 # Default num_words for imdb.load_data
maxlen = 50        # Used for pad_sequences

# Redefine the model with an Embedding layer
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=32, input_length=maxlen)) # Embedding layer
model.add(SimpleRNN(32, return_sequences=False)) # SimpleRNN layer, input_shape now inferred
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.compile(loss = 'binary_crossentropy',optimizer = 'adam',metrics = ['accuracy'])

In [21]:
history = model.fit(X_train,y_train,epochs = 5,validation_data = (X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 11ms/step - accuracy: 0.5051 - loss: 0.6975 - val_accuracy: 0.5034 - val_loss: 0.6974
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.5050 - loss: 0.6933 - val_accuracy: 0.5044 - val_loss: 0.6939
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.5078 - loss: 0.6929 - val_accuracy: 0.5042 - val_loss: 0.6953
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.5032 - loss: 0.6928 - val_accuracy: 0.5068 - val_loss: 0.6974
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.5101 - loss: 0.6924 - val_accuracy: 0.5046 - val_loss: 0.6947


In [1]:
import numpy as np

docs = ['python is great',
        'machine learning rules',
        'clean code always',
        'debug till it works',
        'git commit and push',
        'stack overflow saves lives',
        'artificial intelligence future',
        'keep it simple stupid',
        'syntax error found',
        'hello world program']

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [3]:
tokenizer.fit_on_texts(docs)

In [4]:
len(tokenizer.word_index)

33

In [5]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[2, 3, 4],
 [5, 6, 7],
 [8, 9, 10],
 [11, 12, 1, 13],
 [14, 15, 16, 17],
 [18, 19, 20, 21],
 [22, 23, 24],
 [25, 1, 26, 27],
 [28, 29, 30],
 [31, 32, 33]]

In [6]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding = 'post')
sequences

array([[ 2,  3,  4,  0],
       [ 5,  6,  7,  0],
       [ 8,  9, 10,  0],
       [11, 12,  1, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24,  0],
       [25,  1, 26, 27],
       [28, 29, 30,  0],
       [31, 32, 33,  0]], dtype=int32)

In [15]:
model = Sequential()
model.add(Embedding(input_dim=34, output_dim = 2)) # input_dim = len(tokenizer.word_index) + 1
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.compile('adam','accuracy')

In [17]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step
[[[-0.0142478  -0.02214123]
  [ 0.02024344 -0.02528464]
  [-0.00649619 -0.02260462]
  [ 0.00250943  0.00791415]]

 [[-0.00955252 -0.03081675]
  [-0.03989111  0.01741281]
  [-0.00023912  0.03431377]
  [ 0.00250943  0.00791415]]

 [[-0.00629207 -0.02337219]
  [ 0.02883122 -0.00332379]
  [-0.01823574  0.04462052]
  [ 0.00250943  0.00791415]]

 [[ 0.01407221 -0.04808413]
  [ 0.02225269 -0.0418949 ]
  [-0.02038215  0.0304401 ]
  [-0.04318856 -0.03041793]]

 [[-0.01440961 -0.0214056 ]
  [ 0.04176     0.01601206]
  [-0.0451207   0.01453699]
  [ 0.03702759  0.04999987]]

 [[-0.04583892 -0.04108394]
  [-0.03788158 -0.02157264]
  [-0.04094087 -0.017399  ]
  [ 0.02143463  0.03037664]]

 [[-0.03676444  0.03044626]
  [-0.04521792  0.01847115]
  [ 0.02269701  0.022832  ]
  [ 0.00250943  0.00791415]]

 [[-0.00708884  0.03274285]
  [-0.02038215  0.0304401 ]
  [ 0.03846459  0.02668991]
  [-0.01469119  0.04839296]]

 [[-0.0155435   0.04407105]
  [-0.02290152 -0.035

In [19]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [28]:
(X_train,y_train),(X_test,y_test) = imdb.load_data(num_words=10000)

In [29]:
X_train = pad_sequences(X_train, padding='post', maxlen=50)
X_test = pad_sequences(X_test, padding='post', maxlen=50)

In [30]:
X_train.shape

(25000, 50)

In [31]:
model = Sequential()

model.add(Embedding(input_dim = 10000,output_dim = 2,input_length = 50))
model.add(SimpleRNN(32,return_sequences = False))
model.add(Dense(1,activation = 'sigmoid'))
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.compile(loss = 'binary_crossentropy',optimizer = 'adam',metrics = ['accuracy'])

In [33]:
history = model.fit(X_train,y_train,epochs = 5,validation_data = (X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - accuracy: 0.6436 - loss: 0.6037 - val_accuracy: 0.7710 - val_loss: 0.4847
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 15ms/step - accuracy: 0.8307 - loss: 0.3908 - val_accuracy: 0.8117 - val_loss: 0.4165
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 15ms/step - accuracy: 0.8730 - loss: 0.3119 - val_accuracy: 0.8071 - val_loss: 0.4372
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 14ms/step - accuracy: 0.8978 - loss: 0.2609 - val_accuracy: 0.7892 - val_loss: 0.4702
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - accuracy: 0.9166 - loss: 0.2191 - val_accuracy: 0.7952 - val_loss: 0.5125
